apiVersion: v1
kind: Service
metadata:
  name: downstreamgo
  labels:
    app: downstreamgo
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: downstreamgo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: downstreamgo-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: downstreamgo
        version: v1
    spec:
      containers:
      - name: downstreamgo
        image: phanibalaji/istio-sample-images:downstream-go-v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: downstreamgo
spec:
  host: downstreamgo
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: downstreamgo
spec:
  hosts:
    - downstreamgo
  http:
  - route:
    - destination:
        host: downstreamgo
        subset: v1
    timeout: 2s