apiVersion: v1
kind: Service
metadata:
  name: upstreamnode
  labels:
    app: upstreamnode
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: upstreamnode
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: upstreamnode-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: upstreamnode
        version: v1
    spec:
      containers:
      - name: upstreamnode
        image: phanibalaji/istio-sample-images:upstream-node-v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: upstreamnode
spec:
  host: upstreamnode
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: upstreamnode
spec:
  hosts:
    - upstreamnode
  http:
  - fault:
      delay:
        percent: 100
        fixedDelay: 4s
    route:
    - destination:
        host: upstreamnode
        subset: v1
