apiVersion: v1
kind: Service
metadata:
  name: downstreamgo
  labels:
    app: downstreamgo
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: downstreamgo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: downstreamgo-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: downstreamgo
        version: v1
    spec:
      containers:
      - name: downstreamgo
        image: phanibalaji/istio-sample-images:downstream-go-v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
